# services/priority_synonyms.py

priority_synonyms = {
    "dog": ["dog", "dogs", "puppy", "puppies", "canine", "pet"],
    "cat": ["cat", "cats", "kitten", "kittens", "feline", "pet"],
    "horse": ["horse", "horses", "pony", "foal", "mare", "stallion"],
    "cow": ["cow", "cows", "calf", "calves", "bull", "ox"],
    "sheep": ["sheep", "lamb", "lambs", "ewe", "ram"],
    "goat": ["goat", "goats", "kid", "billy", "nanny"],
    "pig": ["pig", "pigs", "piglet", "hog", "swine"],
    "chicken": ["chicken", "chickens", "hen", "rooster", "pullet", "cock"],
    "duck": ["duck", "ducks", "duckling", "drake"],
    "bird": ["bird", "birds", "sparrow", "parrot", "pigeon"],
    "fish": ["fish", "fishes", "goldfish", "salmon", "trout", "shark"],
    "lion": ["lion", "lions", "cub", "big cat", "predator"],
    "tiger": ["tiger", "tigers", "tigress", "cub", "big cat"],
    "bear": ["bear", "bears", "cub", "grizzly", "polar bear", "panda"],
    "elephant": ["elephant", "elephants", "calf", "mammoth", "giant"],
    "giraffe": ["giraffe", "giraffes", "calf", "tall animal"],
    "zebra": ["zebra", "zebras", "foal", "striped horse"],
    "monkey": ["monkey", "monkeys", "ape", "chimp", "gorilla"],
    "rabbit": ["rabbit", "rabbits", "bunny", "hare"],
    "mouse": ["mouse", "mice", "rodent"],
    "rat": ["rat", "rats", "rodent"],
    "deer": ["deer", "fawn", "stag", "doe", "buck"],
    "fox": ["fox", "foxes", "cub", "vixen"],
    "wolf": ["wolf", "wolves", "cub", "canine", "pack"],
    "man": ["man", "men", "male", "guy", "gentleman", "person"],
    "woman": ["woman", "women", "female", "lady", "mom", "mother", "person"],
    "child": ["child", "children", "kid", "kids", "toddler", "baby", "boy", "girl"],
    "baby": ["baby", "infant", "newborn", "toddler"],
    "boy": ["boy", "boys", "kid", "child", "son"],
    "girl": ["girl", "girls", "daughter", "kid", "child"],
    "family": ["family", "parents", "mother", "father", "kids", "children", "relatives", "household"],
    "father": ["father", "dad", "daddy", "papa", "parent", "man"],
    "mother": ["mother", "mom", "mum", "mommy", "mama", "parent", "woman"],
    "parent": ["parent", "parents", "guardian", "mother", "father"],
    "grandmother": ["grandmother", "grandma", "granny", "nana"],
    "grandfather": ["grandfather", "grandpa", "granddad", "papa"],
    "friend": ["friend", "friends", "buddy", "pal", "companion", "mate"],
    "teacher": ["teacher", "professor", "lecturer", "instructor"],
    "student": ["student", "pupil", "learner", "scholar"],
    "doctor": ["doctor", "physician", "medic", "gp"],
    "nurse": ["nurse", "nurses", "healthcare worker"],
    "patient": ["patient", "sick person", "client"],
    "worker": ["worker", "employee", "staff", "laborer"],
    "boss": ["boss", "chief", "manager", "employer"],
    "money": ["money", "cash", "currency", "finance", "wealth"],
    "bank": ["bank", "finance", "institution", "atm"],
    "credit": ["credit", "card", "debt", "loan"],
    "restaurant": ["restaurant", "diner", "cafe", "eatery"],
    "food": ["food", "meal", "cuisine", "dish", "snack"],
    "drink": ["drink", "beverage", "cocktail", "juice", "soda", "water"],
    "coffee": ["coffee", "espresso", "latte", "cappuccino"],
    "tea": ["tea", "green tea", "black tea"],
    "wine": ["wine", "red wine", "white wine"],
    "beer": ["beer", "lager", "ale", "pint"],
    "pizza": ["pizza", "slice", "pie"],
    "burger": ["burger", "hamburger", "sandwich"],
    "cake": ["cake", "dessert", "pie", "pastry"],
    "chocolate": ["chocolate", "candy", "sweet"],
    "bread": ["bread", "loaf", "bun", "toast"],
    "rice": ["rice", "grains", "cereal"],
    "pasta": ["pasta", "spaghetti", "noodles"],
    "fruit": ["fruit", "fruits", "apple", "banana", "orange"],
    "vegetable": ["vegetable", "vegetables", "carrot", "tomato", "potato"],
    "car": ["car", "cars", "auto", "automobile", "vehicle"],
    "bus": ["bus", "coach", "minibus"],
    "train": ["train", "railway", "metro"],
    "plane": ["plane", "airplane", "jet", "aircraft"],
    "ship": ["ship", "boat", "ferry", "yacht"],
    "bicycle": ["bicycle", "bike", "cycle"],
    "motorcycle": ["motorcycle", "bike", "scooter"],
    "computer": ["computer", "pc", "desktop", "laptop"],
    "laptop": ["laptop", "notebook", "pc"],
    "phone": ["phone", "smartphone", "mobile", "cellphone"],
    "camera": ["camera", "photo camera", "dslr"],
    "television": ["television", "tv", "screen", "monitor"],
    "internet": ["internet", "web", "online"],
    "software": ["software", "app", "program"],
    "music": ["music", "song", "tune", "melody"],
    "sport": ["sport", "sports", "athletics", "game"],
    "football": ["football", "soccer", "ball", "match"],
    "basketball": ["basketball", "ball", "hoops"],
    "tennis": ["tennis", "racket", "match"],
    "golf": ["golf", "club", "ball"],
    "swimming": ["swimming", "pool", "swimmer"],
    "running": ["running", "jogging", "marathon"],
    "holiday": ["holiday", "vacation", "trip", "journey"],
    "travel": ["travel", "trip", "tourism", "journey"],
    "beach": ["beach", "coast", "seashore", "ocean"],
    "mountain": ["mountain", "hill", "peak", "summit"],
    "forest": ["forest", "woods", "jungle"],
    "desert": ["desert", "sand", "dunes"],
    "city": ["city", "town", "urban"],
    "village": ["village", "countryside", "rural"],
    "house": ["house", "home", "residence"],
    "apartment": ["apartment", "flat", "condo"],
    "school": ["school", "college", "university"],
    "office": ["office", "workspace", "corporate"],
    "market": ["market", "bazaar", "shop", "store"],
    "shop": ["shop", "store", "boutique"],
    "clothes": ["clothes", "clothing", "apparel", "garment"],
    "shoes": ["shoes", "footwear", "sneakers"],
    "bag": ["bag", "purse", "backpack", "handbag"],
    "watch": ["watch", "clock", "timepiece"],
    "jewelry": ["jewelry", "ring", "necklace", "bracelet"],
    "toy": ["toy", "toys", "doll", "game"],
    "book": ["book", "books", "novel", "story"],
    "pen": ["pen", "pencil", "marker"],
    "paper": ["paper", "page", "sheet"],
    "gift": ["gift", "present", "surprise"],
    "christmas": ["christmas", "xmas", "holiday", "new year", "festive", "celebration"],
    "easter": ["easter", "egg", "holiday", "celebration"],
    "halloween": ["halloween", "pumpkin", "costume", "trick", "treat"],
    "valentine": ["valentine", "love", "hearts", "romance"],
    "birthday": ["birthday", "party", "celebration", "anniversary", "cake", "festive"],
    "new year": ["new year", "celebration", "fireworks", "eve"],
    "mother day": ["mother day", "mom", "holiday", "celebration"],
    "father day": ["father day", "dad", "holiday", "celebration"],
    "women day": ["women day", "march 8", "holiday"],
    "patrick day": ["patrick day", "st patrick", "shamrock", "irish"],
    "thanksgiving": ["thanksgiving", "turkey", "holiday", "harvest"],
    "independence": ["independence", "july 4", "fireworks"],
    "season": ["season", "winter", "spring", "summer", "autumn", "fall"],
    "winter": ["winter", "snow", "cold", "frost"],
    "spring": ["spring", "flowers", "bloom"],
    "summer": ["summer", "sun", "heat", "vacation"],
    "autumn": ["autumn", "fall", "leaves", "harvest"],
    "nurse": ["nurse", "nurses", "healthcare worker", "medical staff"],
    "dentist": ["dentist", "orthodontist", "dental", "doctor"],
    "police": ["police", "officer", "cop", "law enforcement"],
    "firefighter": ["firefighter", "fireman", "rescuer"],
    "soldier": ["soldier", "army", "military", "troop"],
    "engineer": ["engineer", "developer", "technician"],
    "programmer": ["programmer", "coder", "developer", "software engineer"],
    "farmer": ["farmer", "agriculture", "grower", "peasant"],
    "chef": ["chef", "cook", "culinary", "kitchen"],
    "driver": ["driver", "chauffeur", "operator"],
    "pilot": ["pilot", "aviator", "airman"],
    "sailor": ["sailor", "seaman", "crew"],
    "student": ["student", "pupil", "scholar", "learner"],
    "artist": ["artist", "painter", "illustrator", "creator"],
    "singer": ["singer", "vocalist", "musician"],
    "actor": ["actor", "actress", "performer"],
    "writer": ["writer", "author", "novelist", "poet"],
    "photographer": ["photographer", "cameraman", "photo artist"],
    "model": ["model", "mannequin", "poser"],
    "scientist": ["scientist", "researcher", "biologist", "chemist"],
    "doctor": ["doctor", "physician", "medic", "healthcare"],
    "lawyer": ["lawyer", "attorney", "advocate", "counsel"],
    "judge": ["judge", "justice", "magistrate"],
    "king": ["king", "monarch", "sovereign"],
    "queen": ["queen", "monarch", "royalty"],
    "prince": ["prince", "royalty", "noble"],
    "princess": ["princess", "royalty", "noble"],
    "baby boy": ["baby boy", "infant", "newborn", "male child"],
    "baby girl": ["baby girl", "infant", "newborn", "female child"],
    "teenager": ["teenager", "teen", "adolescent", "youth"],
    "elderly": ["elderly", "senior", "aged", "old person"],
    "couple": ["couple", "pair", "partners", "lovers"],
    "bride": ["bride", "wife", "woman", "lady"],
    "groom": ["groom", "husband", "man", "gentleman"],
    "wedding": ["wedding", "marriage", "ceremony", "nuptials"],
    "anniversary": ["anniversary", "celebration", "jubilee"],
    "party": ["party", "celebration", "event", "gathering"],
    "festival": ["festival", "fair", "carnival", "celebration"],
    "concert": ["concert", "show", "performance", "gig"],
    "parade": ["parade", "march", "celebration"],
    "ceremony": ["ceremony", "ritual", "tradition"],
    "happiness": ["happiness", "joy", "smile", "delight"],
    "sadness": ["sadness", "grief", "tears", "sorrow"],
    "anger": ["anger", "rage", "fury", "wrath"],
    "love": ["love", "romance", "affection", "passion"],
    "friendship": ["friendship", "companionship", "bond", "relationship"],
    "family love": ["family love", "parental care", "affection"],
    "care": ["care", "support", "protection", "help"],
    "health": ["health", "wellness", "fitness", "medicine"],
    "hospital": ["hospital", "clinic", "healthcare", "medical"],
    "pharmacy": ["pharmacy", "drugstore", "chemist"],
    "medicine": ["medicine", "drugs", "pills", "treatment"],
    "vaccine": ["vaccine", "immunization", "shot", "injection"],
    "mask": ["mask", "face mask", "respirator"],
    "virus": ["virus", "infection", "disease", "flu"],
    "covid": ["covid", "coronavirus", "pandemic", "disease"],
    "heart": ["heart", "cardiac", "love", "organ"],
    "brain": ["brain", "mind", "intellect", "head"],
    "eye": ["eye", "eyes", "vision", "sight"],
    "ear": ["ear", "ears", "hearing", "listen"],
    "mouth": ["mouth", "lips", "smile", "teeth"],
    "tooth": ["tooth", "teeth", "molar", "incisor"],
    "hand": ["hand", "hands", "palm", "finger"],
    "foot": ["foot", "feet", "toe", "leg"],
    "leg": ["leg", "legs", "thigh", "calf"],
    "arm": ["arm", "arms", "shoulder"],
    "head": ["head", "skull", "face", "hair"],
    "hair": ["hair", "hairstyle", "locks", "curls"],
    "skin": ["skin", "dermis", "epidermis"],
    "color": ["color", "hue", "shade", "tone"],
    "red": ["red", "scarlet", "crimson", "ruby"],
    "blue": ["blue", "navy", "azure", "sky"],
    "green": ["green", "emerald", "lime", "olive"],
    "yellow": ["yellow", "gold", "amber", "lemon"],
    "orange": ["orange", "tangerine", "citrus"],
    "purple": ["purple", "violet", "lavender"],
    "pink": ["pink", "rose", "magenta", "blush"],
    "white": ["white", "snow", "pearl", "ivory"],
    "black": ["black", "dark", "ebony", "jet"],
    "gray": ["gray", "grey", "silver", "ash"],
    "gold": ["gold", "golden", "metal"],
    "silver": ["silver", "platinum", "metal"],
    "money": ["money", "cash", "finance", "wealth"],
    "coin": ["coin", "coins", "currency", "penny"],
    "dollar": ["dollar", "usd", "money", "currency"],
    "euro": ["euro", "eur", "currency", "money"],
    "pound": ["pound", "gbp", "currency", "sterling"],
    "yen": ["yen", "jpy", "currency", "money"],
    "bitcoin": ["bitcoin", "crypto", "currency", "btc"],
    "blockchain": ["blockchain", "crypto", "ledger"],
    "banknote": ["banknote", "bill", "money", "cash"],
    "credit card": ["credit card", "debit card", "payment"],
    "wallet": ["wallet", "purse", "money holder"],
    "shopping": ["shopping", "buying", "retail", "ecommerce"],
    "sale": ["sale", "discount", "offer", "promotion"],
    "gift card": ["gift card", "voucher", "coupon"],
    "store": ["store", "shop", "boutique"],
    "market": ["market", "bazaar", "commerce", "mall"],
    "online shop": ["online shop", "ecommerce", "store"],
    "cart": ["cart", "basket", "trolley"],
    "delivery": ["delivery", "shipping", "courier"],
    "package": ["package", "parcel", "box"],
    "box": ["box", "container", "crate"],
    "bag": ["bag", "purse", "backpack", "handbag"],
    "suitcase": ["suitcase", "luggage", "baggage"],
    "travel": ["travel", "trip", "journey", "vacation"],
    "ticket": ["ticket", "pass", "boarding"],
    "passport": ["passport", "id", "travel document"],
    "map": ["map", "atlas", "navigation", "plan"],
    "compass": ["compass", "navigation", "direction"],
    "hotel": ["hotel", "motel", "inn", "hostel"],
    "room": ["room", "suite", "apartment"],
    "bed": ["bed", "bunk", "mattress"],
    "chair": ["chair", "seat", "stool"],
    "table": ["table", "desk", "counter"],
    "sofa": ["sofa", "couch", "divan"],
    "lamp": ["lamp", "light", "lantern"],
    "window": ["window", "glass", "pane"],
    "door": ["door", "gate", "entrance"],
    "floor": ["floor", "ground", "tile"],
    "roof": ["roof", "ceiling", "cover"],
    "wall": ["wall", "barrier", "partition"],
    "kitchen": ["kitchen", "cookroom", "cuisine"],
    "bathroom": ["bathroom", "toilet", "restroom", "washroom"],
    "garden": ["garden", "yard", "lawn", "backyard"],
    "park": ["park", "playground", "green area"],
    "street": ["street", "road", "avenue", "lane"],
    "bridge": ["bridge", "viaduct", "overpass"],
    "river": ["river", "stream", "brook"],
    "lake": ["lake", "pond", "reservoir"],
    "sea": ["sea", "ocean", "water"],
    "sky": ["sky", "heavens", "clouds"],
    "sun": ["sun", "sunlight", "daylight"],
    "moon": ["moon", "lunar", "crescent"],
    "star": ["star", "stars", "constellation"],
    "planet": ["planet", "world", "earth", "mars"],
    "space": ["space", "universe", "cosmos", "galaxy"],
    "rocket": ["rocket", "spaceship", "shuttle"],
    "astronaut": ["astronaut", "cosmonaut", "spaceman"],
    "satellite": ["satellite", "orbiter", "spacecraft"],
    "football": ["football", "soccer", "ball game", "match"],
    "basketball": ["basketball", "nba", "ball", "hoops"],
    "tennis": ["tennis", "racket", "court", "game"],
    "golf": ["golf", "golfer", "club", "tournament"],
    "baseball": ["baseball", "mlb", "bat", "pitch"],
    "hockey": ["hockey", "ice hockey", "stick", "puck"],
    "ski": ["ski", "skiing", "snowboard", "slopes"],
    "swimming": ["swimming", "pool", "diving", "water sport"],
    "running": ["running", "jogging", "marathon", "athletics"],
    "cycling": ["cycling", "biking", "bicycle", "racing"],
    "boxing": ["boxing", "fighter", "ring", "match"],
    "yoga": ["yoga", "meditation", "asana", "wellness"],
    "gym": ["gym", "fitness", "workout", "exercise"],
    "weightlifting": ["weightlifting", "strength", "barbell"],
    "surfing": ["surfing", "surfboard", "ocean sport"],
    "volleyball": ["volleyball", "beach volleyball", "spike"],
    "rugby": ["rugby", "tackle", "scrum", "ball"],
    "karate": ["karate", "martial arts", "dojo"],
    "judo": ["judo", "martial arts", "grappling"],
    "climbing": ["climbing", "rock climbing", "mountaineering"],
    "hiking": ["hiking", "trekking", "walk", "outdoors"],
    "camping": ["camping", "tent", "outdoor", "backpacking"],
    "fishing": ["fishing", "angler", "catch", "rod"],
    "hunting": ["hunting", "hunter", "rifle", "outdoors"],

    "pizza": ["pizza", "slice", "pizzeria", "italian food"],
    "burger": ["burger", "hamburger", "sandwich", "fast food"],
    "pasta": ["pasta", "spaghetti", "noodles", "italian food"],
    "sushi": ["sushi", "japanese food", "rolls"],
    "salad": ["salad", "vegetables", "greens", "healthy"],
    "soup": ["soup", "broth", "stew"],
    "steak": ["steak", "beef", "meat", "grill"],
    "chicken": ["chicken", "poultry", "meat"],
    "fish": ["fish", "seafood", "trout", "salmon"],
    "shrimp": ["shrimp", "prawns", "seafood"],
    "crab": ["crab", "lobster", "shellfish"],
    "egg": ["egg", "eggs", "omelette", "boiled egg"],
    "bread": ["bread", "loaf", "toast", "bun"],
    "cake": ["cake", "dessert", "pastry", "birthday cake"],
    "cookie": ["cookie", "biscuit", "sweet"],
    "ice cream": ["ice cream", "gelato", "dessert", "cone"],
    "chocolate": ["chocolate", "candy", "sweet"],
    "candy": ["candy", "sweets", "lollipop", "treat"],
    "honey": ["honey", "bee product", "nectar"],
    "cheese": ["cheese", "dairy", "parmesan", "mozzarella"],
    "butter": ["butter", "dairy", "spread"],
    "milk": ["milk", "dairy", "drink"],
    "coffee": ["coffee", "espresso", "cappuccino", "latte"],
    "tea": ["tea", "green tea", "black tea", "herbal"],
    "juice": ["juice", "orange juice", "fruit drink"],
    "wine": ["wine", "red wine", "white wine", "champagne"],
    "beer": ["beer", "lager", "ale", "brew"],
    "cocktail": ["cocktail", "drink", "martini", "mojito"],
    "water": ["water", "bottle", "mineral", "drink"],
    "smoothie": ["smoothie", "milkshake", "fruit drink"],

    "car": ["car", "automobile", "vehicle", "sedan"],
    "bus": ["bus", "coach", "minibus", "transport"],
    "train": ["train", "railway", "metro", "subway"],
    "truck": ["truck", "lorry", "pickup"],
    "motorcycle": ["motorcycle", "bike", "scooter"],
    "bicycle": ["bicycle", "bike", "cycling"],
    "plane": ["plane", "airplane", "jet"],
    "boat": ["boat", "ship", "ferry", "yacht"],
    "helicopter": ["helicopter", "chopper", "aircraft"],
    "tram": ["tram", "trolley", "streetcar"],
    "subway": ["subway", "metro", "underground train"],
    "taxi": ["taxi", "cab", "ride"],

    "spring": ["spring", "season", "bloom", "flowers"],
    "summer": ["summer", "heat", "vacation", "holiday"],
    "autumn": ["autumn", "fall", "season", "harvest"],
    "winter": ["winter", "snow", "cold", "season"],

    "christmas tree": ["christmas tree", "xmas tree", "holiday decoration"],
    "santa claus": ["santa claus", "father christmas", "saint nick"],
    "reindeer": ["reindeer", "caribou", "xmas animal"],
    "gift": ["gift", "present", "box", "surprise"],
    "fireworks": ["fireworks", "sparklers", "explosives"],
    "lantern": ["lantern", "light", "lamp", "festival light"],
    "pumpkin": ["pumpkin", "halloween pumpkin", "jack o lantern"],
    "ghost": ["ghost", "spirit", "phantom"],
    "witch": ["witch", "wizard", "sorceress"],
    "skeleton": ["skeleton", "bones", "halloween"],
    "egg hunt": ["egg hunt", "easter eggs", "children activity"],
    "valentine": ["valentine", "love day", "february 14"],
    "st patrick": ["st patrick", "irish day", "green celebration"],
    "mother": ["mother", "mom", "mommy", "mum"],
    "father": ["father", "dad", "daddy", "papa"],
    "teacher": ["teacher", "educator", "professor"],
    "student life": ["student life", "school", "study"],
    "exam": ["exam", "test", "school test"],

    "computer": ["computer", "pc", "desktop", "mac"],
    "laptop": ["laptop", "notebook", "macbook"],
    "phone": ["phone", "smartphone", "mobile"],
    "tablet": ["tablet", "ipad", "device"],
    "camera": ["camera", "photo camera", "dslr"],
    "printer": ["printer", "scanner", "copy machine"],
    "keyboard": ["keyboard", "keys", "typing"],
    "mouse": ["mouse", "computer mouse", "pointer"],
    "headphones": ["headphones", "earphones", "earbuds"],
    "tv": ["tv", "television", "screen"],
    "radio": ["radio", "broadcast", "fm"],
    "game": ["game", "videogame", "console"],
    "console": ["console", "playstation", "xbox", "nintendo"],

    "apple": ["apple", "fruit", "red apple", "green apple"],
    "banana": ["banana", "fruit", "plantain"],
    "orange fruit": ["orange fruit", "citrus", "mandarin"],
    "pear": ["pear", "fruit", "nashi"],
    "peach": ["peach", "nectarine", "fruit"],
    "plum": ["plum", "fruit", "stone fruit"],
    "grape": ["grape", "vine", "fruit", "wine"],
    "watermelon": ["watermelon", "melon", "fruit"],
    "melon": ["melon", "cantaloupe", "fruit"],
    "strawberry": ["strawberry", "berry", "fruit"],
    "blueberry": ["blueberry", "berry", "fruit"],
    "raspberry": ["raspberry", "berry", "fruit"],
    "cherry": ["cherry", "fruit", "stone fruit"],
    "lemon": ["lemon", "citrus", "fruit"],
    "lime": ["lime", "citrus", "fruit"],
    "coconut": ["coconut", "tropical fruit", "nut"],
    "pineapple": ["pineapple", "tropical fruit", "ananas"],

    "school": ["school", "education", "class", "study"],
    "classroom": ["classroom", "school room", "learning"],
    "university": ["university", "college", "campus"],
    "library": ["library", "books", "reading"],
    "book": ["book", "novel", "textbook"],
    "pen": ["pen", "ballpen", "fountain pen"],
    "pencil": ["pencil", "crayon", "draw"],
    "notebook": ["notebook", "copybook", "exercise book"],
    "bag school": ["bag school", "backpack", "satchel"],
    "chalk": ["chalk", "blackboard", "drawing"],
    "blackboard": ["blackboard", "chalkboard", "board"],
    "exam paper": ["exam paper", "test sheet", "assessment"],
    "graduation": ["graduation", "diploma", "degree"],
    "diploma": ["diploma", "certificate", "degree"],
    "teacher desk": ["teacher desk", "school table"],

}
